id: opecha:P009550
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS88140
  title: བོད་ལུགས་གསོ་རིག་གི་དགོངས་དོན་ཡུལ་རྐྱེན་གྲུམ་ཚིགས་ཆེན་ནད་ཀྱི་གོ་དོན་བཅས་ཐབས་སྨྲ་བའི་མཆོག་གཏེར
  volume: ''
  author: ''
