id: I9442689C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:06:38+00:00'
last_modified: '2022-06-08T11:49:32.262762+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS88140
  title: བོད་ལུགས་གསོ་རིག་གི་དགོངས་དོན་ཡུལ་རྐྱེན་གྲུམ་ཚིགས་ཆེན་ནད་ཀྱི་གོ་དོན་བཅས་ཐབས་སྨྲ་བའི་མཆོག་གཏེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4D19:
      image_group_id: I1GS88142
      title: ''
      total_pages: 358
      order: 1
      base_file: 4D19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
